import type { ThemePlugin } from "../../../plugin/frontend-types/types/plugin";

export const darkTheme: ThemePlugin = {
  name: "dark",
  description: "Default dark theme",
  tokens: {
    "--color-bg-base": "#111827",
    "--color-surface-1": "#1f2937",
    "--color-surface-2": "#374151",
    "--color-surface-3": "#4b5563",
    "--color-overlay": "rgb(0 0 0 / 0.6)",
    "--color-text-primary": "rgba(255, 255, 255, 0.87)",
    "--color-text-secondary": "#d1d5db",
    "--color-text-muted": "#9ca3af",
    "--color-text-faint": "#6b7280",
    "--color-accent": "#2563eb",
    "--color-accent-hover": "#3b82f6",
    "--color-accent-subtle": "#60a5fa",
    "--color-accent-muted": "#93c5fd",
    "--color-accent-dim": "rgb(30 58 138 / 0.6)",
    "--color-danger": "#b91c1c",
    "--color-danger-hover": "#dc2626",
    "--color-danger-subtle": "#f87171",
    "--color-danger-strong": "#ef4444",
    "--color-success": "#22c55e",
    "--color-success-subtle": "#4ade80",
    "--color-success-strong": "#16a34a",
    "--color-warning": "#facc15",
    "--color-warning-strong": "#eab308",
    "--color-border": "#374151",
    "--color-border-subtle": "#4b5563",
    "--color-border-strong": "#6b7280",
    "--color-chip-bg": "#374151",
    "--color-chip-text": "#d1d5db",
    "--color-chip-hover": "#60a5fa",
    "--color-tab-bg": "#ffffff",
    "--color-tab-bg-active": "#9ca3af",
    "--color-tab-bg-hover": "#e5e7eb",
    "--color-placeholder": "#d1d5db",
    "--color-progress-track": "#e5e7eb",
    "--color-badge-static": "rgb(88 28 135 / 0.6)",
    "--color-badge-static-text": "#d8b4fe",
    "--color-link": "#646cff",
    "--color-link-hover": "#535bf2",
  },
  preview: { accent: "#2563eb", background: "#111827" },
};

export const lightTheme: ThemePlugin = {
  name: "light",
  description: "Light theme",
  tokens: {
    "--color-bg-base": "#f9fafb",
    "--color-surface-1": "#ffffff",
    "--color-surface-2": "#f3f4f6",
    "--color-surface-3": "#e5e7eb",
    "--color-overlay": "rgb(0 0 0 / 0.5)",
    "--color-text-primary": "rgba(17, 24, 39, 0.9)",
    "--color-text-secondary": "#374151",
    "--color-text-muted": "#6b7280",
    "--color-text-faint": "#9ca3af",
    "--color-accent": "#2563eb",
    "--color-accent-hover": "#1d4ed8",
    "--color-accent-subtle": "#3b82f6",
    "--color-accent-muted": "#1e40af",
    "--color-accent-dim": "rgb(219 234 254 / 0.8)",
    "--color-danger": "#b91c1c",
    "--color-danger-hover": "#991b1b",
    "--color-danger-subtle": "#dc2626",
    "--color-danger-strong": "#ef4444",
    "--color-success": "#16a34a",
    "--color-success-subtle": "#22c55e",
    "--color-success-strong": "#15803d",
    "--color-warning": "#d97706",
    "--color-warning-strong": "#b45309",
    "--color-border": "#e5e7eb",
    "--color-border-subtle": "#d1d5db",
    "--color-border-strong": "#9ca3af",
    "--color-chip-bg": "#e5e7eb",
    "--color-chip-text": "#1f2937",
    "--color-chip-hover": "#93c5fd",
    "--color-tab-bg": "#f3f4f6",
    "--color-tab-bg-active": "#d1d5db",
    "--color-tab-bg-hover": "#e5e7eb",
    "--color-placeholder": "#e5e7eb",
    "--color-progress-track": "#d1d5db",
    "--color-badge-static": "rgb(243 232 255 / 0.8)",
    "--color-badge-static-text": "#7e22ce",
    "--color-link": "#2563eb",
    "--color-link-hover": "#1d4ed8",
  },
  preview: { accent: "#2563eb", background: "#f9fafb" },
};

export const standardThemes: ThemePlugin[] = [darkTheme, lightTheme];
