on:
  push:

jobs:
  lint-server:
    name: Lint Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Lint
        working-directory: ./server
        run: npm run lint:check

      - name: Style
        working-directory: ./server
        run: npm run style:check

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint
        working-directory: ./frontend
        run: npm run lint:check

      - name: Style
        working-directory: ./frontend
        run: npm run style:check

  build-server:
    name: Build Server
    needs: lint-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Build
        working-directory: ./server
        run: npm run build

  build-frontend:
    name: Build Frontend
    needs: lint-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build
