on: 
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    name: Tag Version

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/semantic-version
        id: version
        with:
          is_beta: ${{ github.ref_name != 'main' }}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          message: "chore: release v${{ steps.version.outputs.version }}"
          tag_exists_error: false
